### PR TITLE
Add CM0+ Support for Multi-Core Devices

### PR DESCRIPTION
**Pull request by DavidLesnjak**

### CODE REVIEW

**Comment by jkrech** [comment]
@DavidLesnjak which of the files are worth reviewing. Most of the files seem to be reference files for validation purposes?!

**Comment by DavidLesnjak** [comment]
> @DavidLesnjak which of the files are worth reviewing. Most of the files seem to be reference files for validation purposes?!

Only stm32CubeMX.go. The remaining code changes are solely for validation purposes, as you've already noticed.

**Review by bgn42 — APPROVED** [review]
lgtm

**Comment by jkrech** [comment]
@DavidLesnjak  leaving merging to you depending on whether you think you will work more on code coverage.

**Pull request merged**
